=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

OpenAPI spec version: 0.7.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EVEOpenAPI::GetUniverseStructuresStructureIdPosition
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetUniverseStructuresStructureIdPosition' do
  before do
    # run before each test
    @instance = EVEOpenAPI::GetUniverseStructuresStructureIdPosition.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetUniverseStructuresStructureIdPosition' do
    it 'should create an instance of GetUniverseStructuresStructureIdPosition' do
      expect(@instance).to be_instance_of(EVEOpenAPI::GetUniverseStructuresStructureIdPosition)
    end
  end
  describe 'test attribute "x"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "y"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "z"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

